### ISSUE TITLE
User

### ISSUE THREAD

**Issue by lukasoppermann** [lukasoppermann/formandsystem-cms#112]
## Login / Logout
- Login
- [ ] Logout
- [ ] Reset password
- [ ] Verify email
- [ ] Change email with verification
- [ ] Be part of Projects
- [ ] Register / Signup
  - [ ] without pending invite …
- [ ] Auto-add if user was invited to Project
- [ ] Log activities e.g. login, logout, create, invite
